image: docker:latest

stages:
  - build
  - test

maven_build:
  image: maven:3-adoptopenjdk-11
  stage: build
  script:
    - echo "starting script..."
    - mvn install -B -DskipTests
  artifacts:
    paths:
      - target/*.jar


unit_test:
  image: maven:3-adoptopenjdk-11
  stage: test
  script:
    - mvn test

sonar-qube:
  image: maven:3.6.3-jdk-11
  stage: test
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar -Dsonar.qualitygate.wait=true
  allow_failure: true
