version: '3.1'
services:
  db:
    image: mariadb:10.3
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 1234:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db

  application:
    depends_on:
      - db
    build: .
    ports:
    - 8080:8080